param(
  [Parameter(Mandatory)]
  [ValidateRange(1, 52)]
  [int]$WeekNumber,

  [Parameter(Mandatory)]
  [datetime]$StartDate,

  [Parameter(Mandatory)]
  [datetime]$EndDate,

  [string]$Focus = '[одне речення про основний slice роботи]',

  [string]$Status = 'чернетка',

  [ValidateSet('текстовий звіт', 'текстовий звіт + відео')]
  [string]$ReportFormat = 'текстовий звіт',

  [switch]$Force
)

$ErrorActionPreference = 'Stop'

if ($EndDate -lt $StartDate) {
  throw 'EndDate must be on or after StartDate.'
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$reportsDir = Join-Path $repoRoot 'docs\Stage 2\weekly_reports'
$templatePath = Join-Path $reportsDir 'weekly_progress_report_template.md'

if (-not (Test-Path $templatePath)) {
  throw "Weekly report template not found at $templatePath"
}

$weekSlug = 'week-{0:d2}' -f $WeekNumber
$reportPath = Join-Path $reportsDir "$weekSlug-progress-report.md"
$artifactsDir = Join-Path $reportsDir "$weekSlug-artifacts"
$artifactsReadmePath = Join-Path $artifactsDir 'README.md'

if ((Test-Path $reportPath) -and -not $Force) {
  throw "Target report already exists: $reportPath. Re-run with -Force to overwrite it."
}

if (-not (Test-Path $reportsDir)) {
  New-Item -Path $reportsDir -ItemType Directory -Force | Out-Null
}

$template = Get-Content -Path $templatePath -Raw -Encoding UTF8
$periodText = '{0:yyyy-MM-dd} - {1:yyyy-MM-dd}' -f $StartDate, $EndDate

$reportContent = $template
$reportContent = $reportContent.Replace('# Тиждень XX. Щотижневий звіт', "# Тиждень $WeekNumber. Щотижневий звіт")
$reportContent = $reportContent.Replace('- Період: `YYYY-MM-DD - YYYY-MM-DD`', ('- Період: `{0}`' -f $periodText))
$reportContent = $reportContent.Replace('- Статус: `чернетка | готово до подачі`', ('- Статус: `{0}`' -f $Status))
$reportContent = $reportContent.Replace('- Формат: `текстовий звіт | текстовий звіт + відео`', ('- Формат: `{0}`' -f $ReportFormat))
$reportContent = $reportContent.Replace('- Фокус тижня: `[одне речення про основний slice роботи]`', "- Фокус тижня: $Focus")

$headerNote = @(
  '<!-- Generated by scripts/local/new-stage2-weekly-report.ps1 -->',
  '<!-- Replace placeholders, add screenshots/video links, and trim any non-relevant sections before submission. -->',
  ''
) -join [Environment]::NewLine

Set-Content -Path $reportPath -Value ($headerNote + $reportContent) -Encoding UTF8

if (-not (Test-Path $artifactsDir)) {
  New-Item -Path $artifactsDir -ItemType Directory -Force | Out-Null
}

$artifactsReadme = (@'
# Week {0} Artifacts

Use this folder for weekly report evidence that should stay close to the report draft.

- Add screenshots here and reference them from `{1}-progress-report.md`.
- Add a text file with a screencast or Loom/YouTube link if you record video.
- Keep filenames stable enough that you can reference them from the report without renaming them at the last minute.

Suggested naming:

- `screenshot-01-dashboard.png`
- `screenshot-02-tests.png`
- `video-link.txt`
'@) -f $WeekNumber, $weekSlug

Set-Content -Path $artifactsReadmePath -Value $artifactsReadme -Encoding UTF8

$sinceText = $StartDate.ToString('yyyy-MM-dd')
$untilText = $EndDate.AddDays(1).ToString('yyyy-MM-dd')

Write-Host "Generated: $reportPath" -ForegroundColor Green
Write-Host "Artifacts: $artifactsDir" -ForegroundColor Green
Write-Host 'Suggested evidence commands:' -ForegroundColor Cyan
Write-Host "  git log --oneline --since '$sinceText' --until '$untilText'"
Write-Host "  bd ready --json"
Write-Host "  pwsh .\scripts\local\run-local-mvp-smoke.ps1 -SkipStart"