#!/usr/bin/env python3
"""Generate or refresh folder README files for active repository directories."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
import re
import sys
from typing import Iterable, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
AUTO_START = "<!-- AUTOGENERATED FOLDER INDEX:START -->"
AUTO_END = "<!-- AUTOGENERATED FOLDER INDEX:END -->"

RECURSIVE_ROOTS = (
    "src",
    "scripts",
    "tests",
    "docs",
    "energy_ml",
    "dashboard",
    "docker",
    "deploy",
)

TOP_LEVEL_ONLY_ROOTS = (
    ".github",
    "archive",
    "artifacts",
    "data",
    "logs",
    "models",
    "plots",
    "projects",
)

SKIP_DIR_NAMES = {
    ".git",
    ".venv",
    ".vscode",
    ".pytest_cache",
    ".desloppify",
    ".beads",
    ".claude",
    ".kilocode",
    ".playwright-mcp",
    ".nuxt",
    ".output",
    "node_modules",
    "__pycache__",
}

SKIP_RELATIVE_PREFIXES = (
    "docs/archive",
    "scripts/archive",
    "energy_ml/outputs",
)

DIRECTORY_DESCRIPTIONS = {
    "": "Repository root for the Smart Energy AI modular monolith.",
    ".github": "Repository automation, workflow, and Copilot-specific instruction files.",
    "archive": "Legacy material retained for reference only; not part of the active runtime.",
    "artifacts": "Generated artifacts and exported outputs from local runs and experiments.",
    "dashboard": "Active Nuxt dashboard application and server-side operator API surface.",
    "dashboard/app": "Nuxt application routes, layouts, plugins, and app-scoped components.",
    "dashboard/components": "Shared dashboard Vue components outside the app-scoped tree.",
    "dashboard/composables": "Nuxt composables and shared frontend state helpers.",
    "dashboard/content": "Content-driven dashboard pages and static content inputs.",
    "dashboard/data": "Dashboard runtime seeds, local snapshots, and generated evidence files.",
    "dashboard/layouts": "Nuxt layout components used by the dashboard routes.",
    "dashboard/pages": "Legacy or compatibility page routes that still live outside app/.",
    "dashboard/public": "Public static assets served directly by the dashboard.",
    "dashboard/scripts": "Dashboard-focused scripts for smoke checks and evidence generation.",
    "dashboard/server": "Nitro server routes, utilities, and backend adapters for the dashboard.",
    "dashboard/stores": "Pinia stores and dashboard state containers.",
    "dashboard/types": "Dashboard TypeScript types and shared contracts.",
    "dashboard/utils": "Dashboard-only utility modules and helper functions.",
    "data": "Local runtime data, Dagster home state, and processed/raw working data.",
    "deploy": "Deployment-specific service files and host integration assets.",
    "docker": "Container, Dagster workspace, and local infrastructure configuration.",
    "docs": "Active repository documentation, runbooks, and technical reference material.",
    "docs/deployment": "Deployment runbooks and infrastructure operation notes.",
    "docs/technical": "Architecture, validation, and backend design reference material.",
    "energy_ml": "Active Python domain package for optimization, simulation, and ML runtime helpers.",
    "energy_ml/assets": "Package-local asset helpers retained for tests and compatibility surfaces.",
    "energy_ml/configs": "Tracked configuration templates and package-level runtime settings.",
    "energy_ml/control": "Battery control integrations and control-loop support modules.",
    "energy_ml/data": "Package-local datasets and training-oriented sample inputs.",
    "energy_ml/energy_ml": "Legacy compatibility package kept only for narrow old import paths.",
    "energy_ml/mlops": "ML serving, registry, monitoring, and forecasting support modules.",
    "energy_ml/optimizer": "Optimization strategies and scheduler-side runtime helpers.",
    "energy_ml/scripts": "Package-local command helpers retained for compatibility and experiments.",
    "energy_ml/simulator": "Detailed battery simulation and physics-oriented runtime helpers.",
    "logs": "Local logs and execution traces from development and operations tooling.",
    "models": "Model artifacts, serialized estimators, and tenant-scoped model outputs.",
    "plots": "Generated visualizations and local chart outputs.",
    "projects": "Nested or external project references retained in the workspace tree.",
    "scripts": "Operational entrypoints, maintenance scripts, and local tooling wrappers.",
    "scripts/ec2": "EC2-specific deployment and bootstrap helpers.",
    "scripts/local": "Local stack launchers and workstation automation helpers.",
    "src": "Primary backend runtime and Dagster asset code for the active system.",
    "src/assets": "Dagster asset modules grouped by domain and responsibility.",
    "src/assets/benchmarks": "Benchmark and performance asset definitions.",
    "src/assets/core": "Core market, weather, feature, forecast, and schedule assets.",
    "src/assets/multi_tenant": "Multi-tenant factories and tenant-scoped asset builders.",
    "src/dagster_api": "Dagster API helpers and service wrappers.",
    "src/data": "Backend-local data helpers and tracked source fixtures.",
    "src/data_pipeline": "Reusable backend helpers extracted from orchestration modules.",
    "src/engines": "Feature-engine implementations and engine-selection helpers.",
    "src/io_managers": "Dagster IO manager implementations and storage adapters.",
    "src/optimization": "Optimization-specific backend helpers and strategy modules.",
    "src/physics": "Battery and energy-physics helper modules.",
    "tests": "Automated validation suites for runtime, scripts, and cleanup guards.",
    "tests/e2e": "End-to-end and browser-facing validation coverage.",
    "tests/integration": "Cross-module and multi-surface integration tests.",
    "tests/performance": "Performance-oriented benchmarks and regression checks.",
    "tests/unit": "Focused unit tests for small backend and script slices.",
}

DIRECTORY_NOTES = {
    "": [
        "Active runtime surfaces are `src/`, `scripts/`, `energy_ml/`, and `dashboard/`.",
        "Generated, cache, and legacy directories are intentionally documented differently; see `docs/technical/REPO_LAYOUT_GUIDE.md`.",
    ],
    ".github": [
        "Keep repository automation and instruction overlays here rather than scattering them across runtime code paths.",
    ],
    "archive": [
        "Treat everything here as reference-only unless a task explicitly targets a legacy surface.",
        "Do not move archived material back into active runtime paths without a deliberate migration step.",
    ],
    "artifacts": [
        "This folder is for generated outputs and should not become a source-of-truth code location.",
    ],
    "dashboard": [
        "This is the canonical Nuxt frontend runtime surface.",
        "Backend cleanup work should avoid changing dashboard code unless the task explicitly includes it.",
    ],
    "data": [
        "Treat contents as local runtime state and working data rather than hand-maintained source files.",
    ],
    "docs": [
        "Keep active reference material here and move dated plans or reports into `docs/archive/`.",
    ],
    "energy_ml": [
        "Use this package for reusable domain/runtime logic, not for new Dagster entrypoints.",
        "The active Dagster code location is `src/definitions.py`.",
    ],
    "logs": [
        "Treat contents as local runtime output rather than reviewed source material.",
    ],
    "models": [
        "Model artifacts here are runtime outputs or checked-in binary assets, not primary code surfaces.",
    ],
    "scripts": [
        "Keep scripts thin and move reusable runtime logic toward `src/` or `energy_ml/`.",
        "`scripts/ml_integration_api.py` remains the canonical backend Python ML bridge.",
    ],
    "src": [
        "`src/definitions.py` is the active Dagster code location for current runtime work.",
        "Prefer placing reusable backend helpers under `src/data_pipeline/` when thinning orchestration modules.",
    ],
    "tests": [
        "Prefer focused validations that match the slice you changed rather than broad test runs.",
    ],
}

DIRECTORY_NAME_DESCRIPTIONS = {
    "api": "API route handlers and related endpoint modules.",
    "app": "Application-scoped routes, layouts, and shared modules.",
    "assets": "Asset modules and asset-support files.",
    "backups": "Backup snapshots and retained copies.",
    "battery": "Battery-related modules and endpoint handlers.",
    "benchmarks": "Benchmark and performance-related modules.",
    "billing": "Billing and tariff-related data or API handlers.",
    "components": "Reusable UI components and presentation modules.",
    "composables": "Composable frontend or runtime helpers.",
    "config": "Configuration files and configuration-oriented modules.",
    "content": "Content-driven documents and source content.",
    "control": "Control-loop logic, commands, and related helpers.",
    "core": "Core runtime modules for the owning surface.",
    "dagster": "Dagster-facing integration modules and service helpers.",
    "dagster_home": "Local Dagster instance storage, event logs, and metadata state.",
    "data": "Tracked data files or data helper modules.",
    "data_pipeline": "Reusable data-processing and validation helpers.",
    "deployment": "Deployment runbooks and infrastructure notes.",
    "ec2": "EC2 deployment and host bootstrap helpers.",
    "engines": "Engine implementations and engine-selection helpers.",
    "io_managers": "Dagster IO manager implementations.",
    "layouts": "Layout components and shared shells.",
    "local": "Local development and workstation helpers.",
    "metrics": "Metrics calculation and reporting modules.",
    "ml": "Machine-learning-facing routes and helpers.",
    "mlflow": "MLflow integration and status surfaces.",
    "multi_tenant": "Multi-tenant factories and tenant-specific modules.",
    "optimization": "Optimization logic and scheduling helpers.",
    "optimizer": "Optimization helpers and strategy modules.",
    "pages": "Route pages and page-specific modules.",
    "physics": "Physics-oriented models and helper modules.",
    "plugins": "Framework plugins and registration modules.",
    "prices": "Price ingestion, normalization, or API surfaces.",
    "processed": "Processed outputs and normalized datasets.",
    "public": "Static assets served directly to clients.",
    "raw": "Raw source data and direct ingests.",
    "renewable": "Renewable forecast and solar-related modules.",
    "results": "Result outputs from runs or experiments.",
    "retraining": "Retraining workflow helpers and retained artifacts.",
    "schedule": "Schedule-related API routes and helper modules.",
    "scripts": "Script entrypoints and automation helpers.",
    "seeds": "Seed files used to initialize local state.",
    "server": "Server-side modules, API routes, and utilities.",
    "settings": "Settings and configuration management surfaces.",
    "simulator": "Simulation and physics-driven helper modules.",
    "stores": "State containers and shared stores.",
    "technical": "Technical reference and design documents.",
    "templates": "Tracked templates and starter files.",
    "tenants": "Tenant-scoped tracked data or configuration.",
    "types": "Shared type definitions and interface contracts.",
    "unit": "Focused unit-test modules for small validation slices.",
    "utils": "Shared helper modules and utility functions.",
}

FILE_DESCRIPTIONS = {
    ".env.example": "Example environment variable file for local setup.",
    "AGENTS.md": "Repository workflow, validation, and execution instructions for coding agents.",
    "customers.yaml": "Tracked multi-tenant customer configuration used by backend and dashboard flows.",
    "docker-compose.yml": "Docker Compose stack definition for local services.",
    "Dockerfile": "Primary container build recipe for the repository runtime.",
    "pytest.ini": "Pytest configuration and shared test runner defaults.",
    "QUICK_START.md": "Quick-start instructions for local development and runtime startup.",
    "README.md": "Folder guide and local index.",
    "requirements-test.txt": "Python test dependency set.",
    "requirements.txt": "Core Python dependency set for the repository runtime.",
    "run_tests.ps1": "PowerShell test runner helper for Windows workflows.",
    "package.json": "Node package manifest and script definitions.",
    "package-lock.json": "Locked npm dependency graph for reproducible installs.",
    "tsconfig.json": "TypeScript compiler configuration.",
    "nuxt.config.ts": "Nuxt application configuration.",
    "tailwind.config.ts": "TailwindCSS configuration.",
    "content.config.ts": "Nuxt Content configuration.",
    "app.vue": "Top-level Vue application shell.",
    "start-dev.ps1": "PowerShell helper to start local dashboard development.",
    "start-dev.sh": "Shell helper to start local dashboard development.",
    "conftest.py": "Pytest fixtures and shared test configuration.",
    "__init__.py": "Package marker and exported module surface.",
}

TEXT_EXTENSIONS = {
    ".md",
    ".py",
    ".ts",
    ".js",
    ".mjs",
    ".vue",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ps1",
    ".sh",
    ".txt",
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or refresh folder README.md files.")
    parser.add_argument("--check", action="store_true", help="Fail if any README changes would be written.")
    args = parser.parse_args()

    targets = collect_target_directories()
    changed_paths: list[Path] = []

    for directory in targets:
        readme_path = directory / "README.md"
        new_content = render_readme(directory, readme_path)
        existing_content = read_text(readme_path)
        if existing_content == new_content:
            continue

        changed_paths.append(readme_path)
        if not args.check:
            readme_path.write_text(new_content, encoding="utf-8")

    print(f"Processed {len(targets)} directories; {len(changed_paths)} README files changed.")
    if changed_paths:
        for path in changed_paths:
            print(path.relative_to(REPO_ROOT).as_posix())

    if args.check and changed_paths:
        return 1
    return 0


def collect_target_directories() -> list[Path]:
    targets = {REPO_ROOT}

    for relative_root in RECURSIVE_ROOTS:
        root_path = REPO_ROOT / relative_root
        if not root_path.exists():
            continue
        for directory in walk_directories(root_path):
            targets.add(directory)

    for relative_root in TOP_LEVEL_ONLY_ROOTS:
        root_path = REPO_ROOT / relative_root
        if root_path.exists() and root_path.is_dir():
            targets.add(root_path)

    return sorted(targets, key=sort_key)


def walk_directories(root_path: Path) -> Iterable[Path]:
    stack = [root_path]
    while stack:
        current = stack.pop()
        if should_skip_directory(current):
            continue
        yield current
        child_directories = [child for child in current.iterdir() if child.is_dir()]
        for child in sorted(child_directories, key=lambda path: path.name.lower(), reverse=True):
            stack.append(child)


def should_skip_directory(path: Path) -> bool:
    if path == REPO_ROOT:
        return False

    relative_path = relative_directory(path)
    parts = [part for part in relative_path.parts if part]
    if any(part in SKIP_DIR_NAMES for part in parts):
        return True
    if any(part.startswith(".tmp_dagster_home_") for part in parts):
        return True

    relative_text = relative_path.as_posix()
    return any(
        relative_text == prefix or relative_text.startswith(prefix + "/")
        for prefix in SKIP_RELATIVE_PREFIXES
    )


def render_readme(directory: Path, readme_path: Path) -> str:
    relative_path = relative_directory(directory).as_posix()
    existing_content = read_text(readme_path)
    manual_content = strip_generated_section(existing_content).strip()
    manual_content = normalize_intro_content(manual_content, relative_path)
    if not manual_content:
        manual_content = build_default_intro(relative_path)

    generated_section = render_generated_section(directory)
    return manual_content.rstrip() + "\n\n" + generated_section.rstrip() + "\n"


def build_default_intro(relative_path: str) -> str:
    title = relative_path or REPO_ROOT.name
    description = describe_directory(relative_path)
    return f"# {title}\n\n{description}"


def normalize_intro_content(content: str, relative_path: str) -> str:
    if not content:
        return content

    non_empty_lines = [line.strip() for line in content.splitlines() if line.strip()]
    expected_title = relative_path or REPO_ROOT.name
    if len(non_empty_lines) == 2 and non_empty_lines[0] == f"# {expected_title}":
        return build_default_intro(relative_path)
    return content


def strip_generated_section(content: str) -> str:
    if AUTO_START not in content or AUTO_END not in content:
        return content

    prefix, _, remainder = content.partition(AUTO_START)
    _, _, suffix = remainder.partition(AUTO_END)
    return (prefix.rstrip() + "\n\n" + suffix.lstrip()).strip()


def render_generated_section(directory: Path) -> str:
    relative_path = relative_directory(directory).as_posix()
    notes = notes_for_directory(relative_path)
    subdirectories = render_subdirectory_index(directory)
    files = render_file_index(directory)

    lines = [AUTO_START, "## Folder Notes", ""]
    for note in notes:
        lines.append(f"- {note}")

    lines.extend(["", "## Index", ""])
    lines.extend(subdirectories)
    lines.append("")
    lines.extend(files)
    lines.append(AUTO_END)
    return "\n".join(lines)


def notes_for_directory(relative_path: str) -> list[str]:
    notes = [
        "Refresh this autogenerated section with `scripts/generate_folder_readmes.py` when folder contents change.",
    ]
    notes.extend(DIRECTORY_NOTES.get(relative_path, []))
    return notes


def render_subdirectory_index(directory: Path) -> list[str]:
    child_directories = []
    for child in sorted(directory.iterdir(), key=lambda path: path.name.lower()):
        if not child.is_dir() or should_skip_directory(child):
            continue
        child_directories.append(child)

    if not child_directories:
        return ["### Subdirectories", "", "- None."]

    lines = ["### Subdirectories", ""]
    for child in child_directories:
        link_target = encode_link(child.name)
        description = describe_directory(relative_directory(child).as_posix())
        lines.append(f"- [{child.name}/]({link_target}) - {description}")
    return lines


def render_file_index(directory: Path) -> list[str]:
    files = [
        child
        for child in sorted(directory.iterdir(), key=lambda path: path.name.lower())
        if child.is_file() and child.name != ".DS_Store"
    ]
    if not any(file_path.name == "README.md" for file_path in files):
        files.append(directory / "README.md")
        files.sort(key=lambda path: path.name.lower())

    if not files:
        return ["### Files", "", "- None."]

    lines = ["### Files", ""]
    for file_path in files:
        link_target = encode_link(file_path.name)
        description = describe_file(file_path)
        lines.append(f"- [{file_path.name}]({link_target}) - {description}")
    return lines


def describe_directory(relative_path: str) -> str:
    if relative_path in DIRECTORY_DESCRIPTIONS:
        return DIRECTORY_DESCRIPTIONS[relative_path]

    name = relative_path.split("/")[-1] if relative_path else REPO_ROOT.name
    if name in DIRECTORY_NAME_DESCRIPTIONS:
        return DIRECTORY_NAME_DESCRIPTIONS[name]
    return f"Directory for {humanize_name(name)}."


def describe_file(path: Path) -> str:
    if path.name in FILE_DESCRIPTIONS:
        return FILE_DESCRIPTIONS[path.name]

    relative_path = path.relative_to(REPO_ROOT).as_posix()
    if relative_path in FILE_DESCRIPTIONS:
        return FILE_DESCRIPTIONS[relative_path]

    if path.suffix == ".py":
        if path.stem.startswith("test_"):
            return f"Focused test module for {humanize_name(path.stem[5:])}."
        docstring = read_python_docstring(path)
        if docstring:
            return docstring
        return f"Python module for {humanize_name(path.stem)}."

    if path.suffix == ".md":
        heading = read_markdown_heading(path)
        if heading:
            return heading
        return f"Markdown guide for {humanize_name(path.stem)}."

    if path.suffix in {".ts", ".tsx"}:
        return f"TypeScript module for {humanize_name(path.stem)}."

    if path.suffix in {".js", ".mjs", ".cjs"}:
        return f"JavaScript module or script for {humanize_name(path.stem)}."

    if path.suffix == ".vue":
        return f"Vue single-file component for {humanize_name(path.stem)}."

    if path.suffix in {".yml", ".yaml"}:
        return f"YAML configuration or data file for {humanize_name(path.stem)}."

    if path.suffix == ".json":
        return f"JSON configuration or data file for {humanize_name(path.stem)}."

    if path.suffix == ".toml":
        return f"TOML configuration for {humanize_name(path.stem)}."

    if path.suffix == ".ps1":
        return f"PowerShell automation script for {humanize_name(path.stem)}."

    if path.suffix == ".sh":
        return f"Shell automation script for {humanize_name(path.stem)}."

    if path.suffix == ".joblib":
        return f"Serialized model artifact for {humanize_name(path.stem)}."

    if path.suffix == ".png":
        return f"PNG image or report artifact for {humanize_name(path.stem)}."

    if path.suffix == ".csv":
        return f"CSV dataset or export for {humanize_name(path.stem)}."

    if path.suffix == ".txt":
        return f"Plain-text note or report for {humanize_name(path.stem)}."

    return f"File for {humanize_name(path.stem or path.name)}."


def read_python_docstring(path: Path) -> str | None:
    try:
        module = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, UnicodeDecodeError):
        return None

    docstring = ast.get_docstring(module)
    return normalize_summary(docstring)


def read_markdown_heading(path: Path) -> str | None:
    text = read_text(path)
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return normalize_summary(stripped.lstrip("# "))
    return None


def normalize_summary(text: str | None) -> str | None:
    if not text:
        return None

    cleaned = re.sub(r"\s+", " ", text.strip())
    if not cleaned:
        return None

    sentence = cleaned.split(". ", 1)[0].rstrip(".")
    if len(sentence) > 120:
        sentence = sentence[:117].rstrip() + "..."
    return sentence + "."


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        if path.suffix not in TEXT_EXTENSIONS:
            return ""
        return ""


def relative_directory(path: Path) -> Path:
    return path.relative_to(REPO_ROOT)


def sort_key(path: Path) -> tuple[int, str]:
    relative = path.relative_to(REPO_ROOT).as_posix()
    if relative == ".":
        return (0, "")
    depth = len(Path(relative).parts)
    return (depth, relative)


def humanize_name(name: str) -> str:
    cleaned = name.replace("_", " ").replace("-", " ")
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if not cleaned:
        return name
    return cleaned


def encode_link(text: str) -> str:
    return text.replace(" ", "%20")


if __name__ == "__main__":
    sys.exit(main())